apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sshUsername }}-{{ include "mychart.fullname" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-ssh
      user: {{ .Values.sshUsername }}
  template:
    metadata:
      labels:
        app: ubuntu-ssh
        user: {{ .Values.sshUsername }}
    spec:
      containers:
      - name: ubuntu
        image: acinwinstack/ubuntu:ssh
        ports:
        - containerPort: 22
        command: ["bash", "-c", "service ssh start; useradd -p $(openssl passwd -1 {{ .Values.sshPassword }}) {{ .Values.sshUsername }}; while true; do sleep 100; done"]
